export const DEFAULT_GAME_WIDTH = 2560;
export const DEFAULT_GAME_HEIGHT = 1440;

export const FIXED_STEP_MS = 1_000 / 60;
export const MAX_FRAME_DELTA_MS = 100;
export const MAX_STEPS_PER_FRAME = 6;

export const GAMEPLAY = {
  playerRadius: 5,
  playerSpeed: 440,
  projectileMargin: 150,
  toolCallHitboxHeight: 15,
  toolCallHitboxMinWidth: 54,
  toolCallHitboxMaxWidth: 386,
  approvalGateThickness: 14,
  approvalGateMinGap: 96,
  approvalGateMaxGap: 144,
  approvalGateTelegraphMs: 1_400,
  approvalGateReachBudgetRatio: 0.72,
  fragmentHitboxHeight: 15,
  maxProjectiles: 56,
  maxHazards: 4,
  maxSequences: 4,
  maxApprovalGates: 2,
  maxRetryChains: 2,
  maxReasoningWaves: 2,
  maxBlackouts: 4,
  toolCallFirstSpawnMs: 850,
  approvalFirstSpawnMs: 12_000,
  compactionFirstSpawnMs: 24_000,
  retryLoopFirstSpawnMs: 36_000,
  reasoningFirstSpawnMs: 48_000,
  parallelAgentsFirstSpawnMs: 60_000,
  reviewLoopFirstSpawnMs: 72_000,
  usageLimitFirstSpawnMs: 84_000,
  blackoutFirstSpawnMs: 97_500,
  toolCallTelegraphMs: 360,
  compactionTelegraphMs: 1_650,
  compactionActiveMs: 520,
  compactionStartSize: 255,
  compactionEndSize: 375,
  compactionMaxViewportRatio: 0.675,
  fullAccessTelegraphMs: 1_800,
  fullAccessActiveMs: 680,
  fullAccessWidth: 340,
  fullAccessHeight: 190,
  fullAccessMaxViewportWidthRatio: 0.72,
  fullAccessMaxViewportHeightRatio: 0.52,
  contextTokenHitboxMinWidth: 22,
  contextTokenHitboxMaxWidth: 76,
  contextTokenHitboxHeight: 13,
  contextTokenBurstMinRadius: 3,
  contextTokenBurstMaxRadius: 26,
  contextTokenGravityPerSecond: 2.4,
  contextTokenHorizontalDragPerSecond: 0.72,
  reasoningTelegraphMs: 2_100,
  reasoningWaveThickness: 16,
  retryChainTelegraphMs: 560,
  retryChainHitboxWidth: 86,
  retryChainHitboxHeight: 15,
  retryChainSpeedGain: 1.12,
  retryChainCompleteMs: 420,
  reviewLoopConvergeMs: 1_450,
  usageLimitConvergeMs: 1_800,
  blackoutStageNineDurationMs: 3_600,
  blackoutStageTenDurationMs: 4_800,
  blackoutTelegraphMs: 720,
  blackoutRevealGraceMs: 180,
  blackoutStageNineIntervalMs: 10_500,
  blackoutStageTenStartIntervalMs: 3_000,
  blackoutMinimumIntervalMs: 1_300,
  blackoutPostStageRampMs: 60_000,
  majorPatternSeparationMs: 360,
  maxConcurrentMajorPatterns: 3,
  smallViewportAreaThresholdRatio: 0.55,
  smallViewportIntervalMultiplier: 1.22,
  endingAtMs: 240_000,
  endingDurationMs: 8_000,
  stageDurationMs: 12_000,
  maxStage: 10,
  difficultyRampMs: 108_000,
} as const;
