import type { AttackSurface } from "./model";

export interface ToolCallEntry {
  label: string;
  surface: AttackSurface;
}

function onSurface(
  surface: AttackSurface,
  labels: readonly string[],
): ToolCallEntry[] {
  return labels.map((label) => ({ label, surface }));
}

const GIT_COMMANDS = [
  "$ git add .",
  "$ git add -A",
  "$ git add -p",
  "$ git add src/game",
  "$ git status",
  "$ git status --short",
  "$ git status --branch --short",
  "$ git diff",
  "$ git diff --stat",
  "$ git diff --check",
  "$ git diff --cached",
  "$ git diff HEAD~1",
  "$ git diff --name-only --diff-filter=ACMRTUXB",
  "$ git log --oneline",
  "$ git log --graph --decorate",
  "$ git log --pretty=format:'%h %ad %s' --date=short",
  "$ git log -5 --stat",
  "$ git show HEAD",
  "$ git show --stat HEAD",
  "$ git commit",
  '$ git commit -m "fix"',
  '$ git commit -m "fix flaky test"',
  '$ git commit -m "one last change"',
  '$ git commit -m "ship context overflow"',
  '$ git commit -m "fix context compaction token gravity"',
  "$ git commit --amend --no-edit",
  "$ git push",
  "$ git push origin main",
  "$ git push --set-upstream origin feature/ui",
  "$ git push --force-with-lease",
  "$ git push origin codex/core-game-foundation",
  "$ git pull",
  "$ git pull --rebase",
  "$ git fetch",
  "$ git fetch --all --prune",
  "$ git switch main",
  "$ git switch -c feature/context",
  "$ git restore .",
  "$ git restore --staged .",
  "$ git restore src/game/core",
  "$ git reset HEAD~1",
  "$ git reset --soft HEAD~1",
  "$ git rebase main",
  "$ git rebase --continue",
  "$ git rebase --abort",
  "$ git merge main",
  "$ git merge --continue",
  "$ git merge --abort",
  "$ git cherry-pick --continue",
  "$ git stash",
  "$ git stash pop",
  "$ git stash list",
  "$ git branch --all",
  "$ git branch -d old-branch",
  "$ git worktree list",
  "$ git worktree prune",
  "$ git clean -nd",
  "$ git tag --list",
  "$ git rev-parse HEAD",
] as const;

const PACKAGE_COMMANDS = [
  "$ pnpm install",
  "$ pnpm install --frozen-lockfile",
  "$ pnpm add phaser",
  "$ pnpm remove package-name",
  "$ pnpm dev",
  "$ pnpm build",
  "$ pnpm check",
  "$ pnpm test",
  "$ pnpm test --run",
  "$ pnpm test --watch",
  "$ pnpm lint",
  "$ pnpm typecheck",
  "$ pnpm exec vite build",
  "$ pnpm exec vitest run",
  "$ pnpm exec vitest run src/game/core",
  "$ pnpm exec vitest run src/game/core/simulation.test.ts",
  "$ pnpm exec tsc --noEmit",
  "$ pnpm outdated",
  "$ pnpm update",
  "$ pnpm why phaser",
  "$ pnpm list --depth 0",
  "$ npm install",
  "$ npm ci",
  "$ npm run dev",
  "$ npm run build",
  "$ npm run lint",
  "$ npm run typecheck",
  "$ npm run test -- --coverage --reporter=verbose",
  "$ npm test",
  "$ npm audit",
  "$ npm outdated",
  "$ npm cache verify",
  "$ npx tsc --noEmit",
  "$ npx eslint src --max-warnings=0",
  "$ npx prettier --check .",
  "$ npx vite build",
  "$ npx vitest run",
  "$ yarn install --immutable",
  "$ yarn dev",
  "$ yarn build",
  "$ yarn test",
  "$ yarn lint",
] as const;

const SHELL_AND_TOOL_COMMANDS = [
  "$ pwd",
  "$ cd src",
  "$ cd src/game",
  "$ cd ..",
  "$ cd -",
  "$ ls",
  "$ ls -la",
  "$ ls src/game",
  "$ find . -name '*.ts'",
  "$ find src -type f",
  "$ mkdir -p dist/assets",
  "$ touch src/game/debug.ts",
  "$ cp .env.example .env.local",
  "$ cp -r public dist/public",
  "$ mv draft.md docs/PROJECT.md",
  "$ rm -r dist",
  "$ rm -f .cache/vite.lock",
  "$ rm *.log",
  "$ cat AGENTS.md",
  "$ cat package.json",
  "$ head -n 40 README.md",
  "$ tail -n 80 debug.log",
  "$ wc -l src/game/core/simulation.ts",
  "$ grep -R TODO src",
  "$ sed -n '1,120p' package.json",
  "$ rg TODO src",
  "$ rg -n 'FIXME|HACK' src",
  "$ rg --files",
  "$ rg --files -g AGENTS.md",
  "$ rg 'context-token' src/game",
  "$ rg -n 'spawn.*Attack' src/game",
  "$ node --test",
  "$ node scripts/verify-production.mjs",
  "$ node dist/server.js",
  "$ tsc --noEmit",
  "$ vite build",
  "$ vite --host 0.0.0.0",
  "$ vitest run",
  "$ vitest run --coverage",
  "$ eslint src --max-warnings=0",
  "$ prettier --check .",
  "$ gh pr status",
  "$ gh pr checks",
  "$ gh pr create --draft",
  "$ docker compose up --build",
  "$ docker compose ps",
  "$ curl -I http://localhost:5173",
  "$ Get-Location",
  "$ Get-ChildItem",
  "$ Get-ChildItem -Recurse -Filter *.ts",
  "$ Get-ChildItem src/game -Recurse -Include *.ts,*.tsx",
  "$ Get-Content package.json",
  "$ Get-Content docs/PROJECT.md -Raw",
  "$ Select-String -Path src/* -Pattern TODO",
  "$ Select-String -Path src/game/**/*.ts -Pattern context",
  "$ Test-Path dist/index.html",
] as const;

const TERMINAL_OUTPUTS = [
  "warning: CRLF incoming",
  "warning: tree is dirty",
  "warning: peer dependency missing",
  "warning: deprecated package",
  "error: command timed out",
  "error: exit code 1",
  "error: failed to push refs",
  "error: pathspec did not match",
  "fatal: not a git repository",
  "TS2322: not assignable",
  "TS2307: cannot find module",
  "ENOENT: file not found",
  "EADDRINUSE: port already in use",
  "ELIFECYCLE: command failed",
  "Tests failed: 1",
  "Build failed in 2.4s",
  "Merge conflict in package.json",
  "Already up to date",
] as const;

const CODEX_ACTIVITY = [
  "+ one more change",
  "+ fixing one last test",
  "[tool] reading AGENTS.md",
  "[tool] reading docs again",
  "[tool] rereading same file",
  "[tool] searching codebase",
  "[tool] waiting for output",
  "[tool] applying patch",
  "[tool] running tests",
  "[tool] checking deployment",
  "[tool] inspecting image",
  "[tool] reading terminal",
  "[tool] updating plan",
  "[tool] verifying production",
  "[context] 84% used",
  "[context] compacting conversation",
  "[context] restoring compressed conversation summary",
  "[context] restoring summary",
  "[review] found one issue",
  "[review] checking changed files",
  "[reasoning] effort xhigh",
  "[reasoning] thinking longer",
  "[usage] 12% left",
  "[usage] resets in 4 days",
  "[agent] waiting for result",
  "[agent] still working",
  "codex: checking diff again",
  "codex: fixing one last test",
  "codex: updating plan again",
  "codex: one last check",
  "codex: context restored maybe",
  "codex: 3 files changed",
  "codex: tests still running",
] as const;

const BROWSER_ACTIVITY = [
  "200 OK /health",
  "204 No Content",
  "301 Moved Permanently",
  "304 Not Modified",
  "400 Bad Request",
  "401 Unauthorized",
  "403 Forbidden",
  "404 Not Found",
  "408 Request Timeout",
  "409 Conflict",
  "418 I'm a Teapot",
  "429 Too Many Requests",
  "500 Internal Server Error",
  "502 Bad Gateway",
  "503 Service Unavailable",
  "504 Gateway Timeout",
  "GET /api/score 500",
  "POST /deploy 429",
  "ERR_CONNECTION_REFUSED",
  "ERR_NAME_NOT_RESOLVED",
  "ERR_TIMED_OUT",
  "ERR_CACHE_MISS",
  "PAGE_CRASHED",
  "PAGE_UNRESPONSIVE",
  "net::ERR_FAILED",
  "net::ERR_INTERNET_DISCONNECTED",
  "net::ERR_CERT_COMMON_NAME_INVALID",
] as const;

export const TOOL_CALL_ENTRIES: readonly ToolCallEntry[] = [
  ...onSurface("terminal", GIT_COMMANDS),
  ...onSurface("terminal", PACKAGE_COMMANDS),
  ...onSurface("terminal", SHELL_AND_TOOL_COMMANDS),
  ...onSurface("terminal", TERMINAL_OUTPUTS),
  ...onSurface("codex", CODEX_ACTIVITY),
  ...onSurface("browser", BROWSER_ACTIVITY),
];
